vim.o.clipboard = "unnamed"
vim.o.confirm = true
vim.o.cursorline = true
vim.o.foldenable = false
vim.o.foldcolumn = "2"
vim.o.foldmethod = "expr"
vim.o.foldexpr = "nvim_treesitter#foldexpr()"
vim.o.ignorecase = true
vim.o.mouse = "a"
vim.o.backup = false
vim.o.writebackup = false
vim.o.showmode = false
vim.o.wrap = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.redrawtime = 20000
vim.o.shiftwidth = 2
vim.o.signcolumn = "number"
vim.o.smartcase = true
vim.o.splitright = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.termguicolors = true
vim.o.updatetime = 300
vim.o.grepprg = "ag --vimgrep $*"
vim.o.grepformat = "%f:%l:%c:%m"
vim.o.completeopt = "menu,menuone,noselect"

-- globals
vim.g.mapleader = " "
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
